const router = require("express").Router();
const companyRouter = require("./company.route");
const userRouter = require("./user.route");
const teamRouter = require("./team.route.js");
const roleRouter = require("./role.route");
const shiftRouter = require("./shift.route");
const taxSlabRouter = require("./taxSlabs.route");
const designationRouter = require("./designation.route");
const leavePolicyRouter = require("./leavePolicy.route");
const attendanceController = require("./attendance.Route");
const permissionTemplateController = require("./permissionTemplate.route");
const permissionsController = require("./permissions.route");
const requestController = require("./requests.route");
const payrollsRouter = require("./payrolls.Route");
const projectManagementRouter = require("./projectManagement.route");
const clientController = require("./client.route");
const focalPersonController = require("./focalPerson.route");
const invoicesTaxSlabController = require("./invoicesTaxSlabs.route");
const invoicesController = require("./invoices.route");
const expensesCategoriesController = require("./expensesCategories.route");
const invoiceTagController = require("./invoiceTag.route");
const invoiceCounterController = require("./invoiceCounter.route");
const bankDetailsController = require("./bankDetails.route");
const expensesController = require("./expenses.route");
const holidaysController = require("./holidays.router");
const tasksController = require("./tasks.router");
const timesheetController = require("./timesheet.route");
const profitLossController = require("./profitLoss.route");
const leadController = require("./leads.router");
// const employeeController = require("./employeeReport.route");
const reportController = require("./report.route");
const taskBoardRouter = require("./taskBoard.Route");
const queryRouter = require("./query.Route");
const admin = require("./admin.route");

router.use("", companyRouter);
router.use("", userRouter);
router.use("", teamRouter);
router.use("", roleRouter);
router.use("", shiftRouter);
router.use("", taxSlabRouter);
router.use("", designationRouter);
router.use("", leavePolicyRouter);
router.use("", attendanceController);
router.use("", permissionTemplateController);
router.use("", permissionsController);
router.use("", requestController);
router.use("", payrollsRouter);
router.use("", projectManagementRouter);
router.use("", clientController);
router.use("", focalPersonController);
router.use("", invoicesTaxSlabController);
router.use("", invoicesController);
router.use("", expensesCategoriesController);
router.use("", invoiceTagController);
router.use("", invoiceCounterController);
router.use("", bankDetailsController);
router.use("", expensesController);
router.use("", holidaysController);
router.use("", tasksController);
router.use("", timesheetController);
router.use("", profitLossController);
router.use("", leadController);
// router.use("", employeeController);
router.use("", reportController);
router.use("", taskBoardRouter);
router.use("", queryRouter);
router.use("", admin);

module.exports = router;
